### ISSUE TITLE
F5BigIpUnnamedObject doesn't have a _get_resource_id_from_path method.

### ISSUE THREAD

**Issue by jonozzz** [erjac77/ansible-module-f5bigip#127]
https://github.com/erjac77/ansible-module-f5bigip/blob/4f4a179dec4edc2d53536d2c8500c3b0c92a027d/library/f5bigip_ltm_virtual_source_address_translation.py#L81

**Comment by erjac77** [comment]
@jonozzz, Thanks for reporting the issue.

Source Address Translation is actually not a "subcollection", but an "array structure", so some refactoring may be needed for this component.

I'll look into it this week.

**Comment by jonozzz** [comment]
Cool! Thanks.

I was going to write a quick and dirty patch to unblock this, but then I decided to open a new bug. It was getting too hairy too quickly :)

**Comment by erjac77** [comment]
@jonozzz, I've just pushed a fix for that. Can you give it a try and let me know if it works as expected?

I removed the Source Address Translation component and added a parameter to Virtual instead, since it is not a subcollection. So to configure a SAT on a Virtual Server, you can do as follow:

```
- name: Add SNAT Pool to a Virtual
  f5bigip_ltm_virtual:
    f5_hostname: "{{ bigip_host }}"
    f5_username: "{{ bigip_username }}"
    f5_password: "{{ bigip_password }}"
    f5_port: "{{ bigip_port }}"
    name: my_http_vs
    partition: Common
    source_address_translation:
      pool: my_snatpool
      type: snat
    state: present
  delegate_to: localhost
```
