### ISSUE TITLE
possible issue with f5bigip_ltm_virtual_profile.py

### ISSUE THREAD

**Issue by jtrotz** [erjac77/ansible-module-f5bigip#20]
Hi,
I am trying to add a HTTP profile to a vServer and have issues when both the profile and the vServer are not in the Common partition. When I use the Ansible task:

    - name: add HTTP profile
      f5bigip_ltm_virtual_profile:
          f5_hostname: "{{Target.host}}"
          f5_username: "{{setup_user}}"
          f5_password: "{{setup_pass}}"
          partition: App_XYZ
          state: "present"
          name: myHttp
          virtual: vs_Server
      delegate_to: localhost

I get this error:

 "msg": "404 Unexpected Error: Not Found for uri: https://bigip1:443/mgmt/tm/ltm/virtual/~App_XYZ~vs_Server/profiles/\nText: u'{\"code\":404,\"message\":\"Object not found - myHttp\",\"errorStack\":[],\"apiError\":1}'"

But: When I look in the GUI I see the profile was correctly associated with the vServer!

When I re-run the playbook it always works fine. The issue is when adding the profile to a vServer for the 1st time.

Maybe my arguments are wrong. Any help would be appreciated - thanks!

-Jim  (jtrotz@gmail.com)

**Comment by erjac77** [comment]
Hi Jim,

Thank you for taking the time to fill a bug report.

Have you tried to specify the partition in the virtual name?

`virtual: /App_XYZ/vs_Server`

I'll update the documentation to better reflect this requirement, and see if I can prevent such an error by assuming that the virtual is in the same partition as the profile when no partition is specified in the virtual name.

Eric

**Comment by jtrotz** [comment]
Thanks for the quick reply!

If add the partition to the Virtual argument I get another error and
nothing happens:

fatal: [localhost -> localhost]: FAILED! => {
    "changed": false,
    "failed": true,
    "invocation": {
        "module_args": {
            "context": null,
            "f5_hostname": "bigip1",
            "f5_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "f5_port": 443,
            "f5_username": "admin",
            "name": "myHttp",
            "partition": "App_XYZ",
            "state": "present",
            "sub_path": null,
            "virtual": "/App_XYZ/vs_Server"
        }
    },
    "msg": "instance names and partitions cannot contain '/', but it's:
/App_XYZ/vs_Server"

I tried using "~" instead of "/" and got the same results..

BTW: it works great when everything is in the /Common partition, but I
can't use it that way.

Thanks again for thelp!

-Jim

**Comment by erjac77** [comment]
Ok, I'll look into it today.

Thank you.

**Comment by erjac77** [comment]
Hi Jim,

I've done some testing, and I can't reproduce the problem. Can you share the version of your BIG-IP, Ansible and Python please?

Also, have you created the HTTP profile before associating it to your VS? Here an example of a minimal playbook that works fine for me:

```
---

- name: Create the Virtual Server
  f5bigip_ltm_virtual:
    f5_hostname: "{{ inventory_hostname }}"
    f5_username: "{{ bigip01_username }}"
    f5_password: "{{ bigip01_password }}"
    f5_port: "{{ bigip01_port }}"
    name: vs_Server
    partition: App_XYZ
    destination: '10.10.10.100:80'
    ip_protocol: tcp
    vlans: net1
    vlans_enabled: true
    state: present
  delegate_to: localhost

- name: Create the HTTP profile
  f5bigip_ltm_profile_http:
    f5_hostname: "{{ inventory_hostname }}"
    f5_username: "{{ bigip01_username }}"
    f5_password: "{{ bigip01_password }}"
    f5_port: "{{ bigip01_port }}"
    name: myHttp
    partition: App_XYZ
    state: present
  delegate_to: localhost

- name: Add the HTTP profile to VS
  f5bigip_ltm_virtual_profile:
    f5_hostname: "{{ inventory_hostname }}"
    f5_username: "{{ bigip01_username }}"
    f5_password: "{{ bigip01_password }}"
    f5_port: "{{ bigip01_port }}"
    name: myHttp
    partition: App_XYZ
    context: all
    virtual: vs_Server
    state: present
  delegate_to: localhost
```
